public class TryCatchDemo {

	public static void main(String[] args) {
		int arr[] = new int[5];
		try {
			System.out.println("First Line");
			int ans = 10 / 2;
			System.out.println("After division");
			System.out.println(arr[3]);
			System.out.println("Last Line");
			String str = null;
		} catch (ArithmeticException e) {
			e.printStackTrace();
			System.out.println("User entered wrong number");
		} catch (ArrayIndexOutOfBoundsException e) {
			e.printStackTrace();
			System.out.println("User entered wrong array");
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println("Something went wrong");
		}

		System.out.println("Line after exception");
	}
}
